version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    networks:
      - default
  php:
    image: php:8.3.2-fpm
    container_name: php_8
    volumes:
      - ./app:/usr/share/nginx/html
      - ./php:/usr/local/etc/php/conf.d
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - default
networks:
  default:
    driver: bridge