version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    environment:
      - ENV=dev
    networks:
      - default
    depends_on:
      - php
  php:
    container_name: php_8
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./app:/usr/share/nginx/html
      - ./php:/usr/local/etc/php/conf.d
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
      - ./xhprof:/var/xhprof/xhprof-2.3.2
    networks:
      - default
volumes:
  xhprof:
networks:
  default:
    driver: bridge